name: C/C++ CI

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    # needed for criterion
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
    - uses: actions/checkout@v2

    - name: compile binary
      run: |
          cmake .
          make
    - name: test
      run: |
          ls bomberman